#! /usr/bin/env python
"""
usage: waitproc [--mines] [--delay DELAY] process command

The process argument is either PID or name.


options:
 --delay: delay of the wait loop
 --mines: search process only in user' processes
"""

import argparse
import os
import time
import subprocess


DEFAULT_DELAY = 60

def main():
    args = parse_arguments()
    process = args.process
    delay = int(args.delay)
    only_mine_procs = args.mines
    cmd = args.cmd
    while True:
        if process_is_running(process, only_mine_procs):
            time.sleep(delay)
        else:
            exec_cmd(cmd)
            break

def parse_arguments():
    parser = argparse.ArgumentParser(description='Execute a command when another process is ended')
    
    parser.add_argument("process", help="the pending process")
    parser.add_argument("cmd", help="command executed when pid finished")
    parser.add_argument('--delay', dest='delay', default=DEFAULT_DELAY, type=int, 
                   help='wait DELAY seconds between two process checks')
    parser.add_argument('--mines', action="store_true",
                   help='search only in processes owned by user')
    return parser.parse_args()

def process_is_running(process, only_mine_procs):
    try:
        pid = int(process)
        return pid in list_processes(only_mine_procs)
    except ValueError:
        return process in list_processes(only_mine_procs, is_pid=False)

def list_processes(only_mine_procs, is_pid=True):
    if is_pid:
        extract_line = lambda line: int(line)
        output_format = "pid"
    else:
        extract_line = lambda line: line.split()[0]
        output_format = "command"
    
    cmd = ['ps', '--no-headers']
    cmd += _mine_cmd(only_mine_procs)
    cmd += ['-eo', output_format]
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    stdout, stderr = p.communicate()
    return [extract_line(line) for line in stdout.split('\n') if line]

def _mine_cmd(only_mine_procs):
    if only_mine_procs:
        return ["--user", str(os.getuid())]
    else:
        return []

def exec_cmd(cmd):
    subprocess.call(cmd.split())


main()

